### ISSUE TITLE
Option to drop all tables before restore

### ISSUE THREAD

**Issue by ivangretsky** [ryancramerdesign/ProcessDatabaseBackups#7]
When I restore a database I expect it to delete all the changes to database made after the backup was made. And ProcessWire makes a lot of those changes. I can see WireDatabaseBackup::restore() has an option to do that (but not sure this module even uses this core class). 

I think dropAll option should be enabled by default, but at least has to be available as an option on restore.

Thank you for this module/ I am using it for years.

**Comment by ryancramerdesign** [comment]
@ivangretsky Makes sense. This option was added the WireDatabaseBackup class last month, so I should add support for it in this module now. You'd have to be on a recent (preferably current) core dev branch for it to appear.

**Comment by ivangretsky** [comment]
Did not notice you made a commit))
Just tested it on a new version and everything seems to work fine. Closing it. Thank you!

**Comment by ivangretsky** [comment]
Wanted tell everybody, but [there is not](https://modules.processwire.com/modules/process-database-backups/) even a forum thread about this module. Maybe it is worth mentioning in a blog?
